export type {
  AccountSummaryDto,
  ArticleGroupDto,
  ArticleGroupItemDto,
  CardChargeResult,
  CardPaymentDto,
  CashierPermissionsDto,
  CatalogInfoDto,
  AllocateReceiptNumberResponse,
  CreateReceiptResponse,
  HoldReceiptDto,
  PosSessionDto,
  ProductDto,
  ProductAttributionDto,
  ProductAllowedSalesmenDto,
  ReceiptDetailDto,
  ReceiptItemDto,
  ReceiptReturnLineDto,
  ReceiptReturnMatchesDto,
  ReceiptReturnSourceDto,
  CashReportDto,
  ReceiptSearchResult,
  ReceiptSummaryDto,
  SaleKind,
  SalesmanDto,
  SectionCashBoxDto,
} from '@fot/shared';

export type { PrintSettingsDto, ReceiptPrintLineDto, ReceiptPrintPreviewDto } from '@fot/shared';
