<Project>
  <PropertyGroup>
    <Version>2.2.64</Version>
    <AssemblyVersion>2.2.64.0</AssemblyVersion>
    <FileVersion>2.2.64.0</FileVersion>
    <InformationalVersion>2.2.64</InformationalVersion>
    <Company>Future of Technology</Company>
    <Product>FOT POS</Product>
    <Authors>Future of Technology</Authors>
    <Copyright>Copyright © Future of Technology</Copyright>
    <NeutralLanguage>ar</NeutralLanguage>
  </PropertyGroup>
</Project>
